export const pricingPlans = [
  {
    name: "Autónomo",
    price: "29",
    description: "Para autoescuelas independientes con hasta 2 instructores.",
    features: [
      "Hasta 100 alumnos activos",
      "2 instructores",
      "Gestión de alumnos y agenda",
      "Facturación básica",
      "App de estudio para alumnos",
      "Soporte por email",
    ],
    cta: "Empezar gratis 30 días",
    highlighted: false,
  },
  {
    name: "Escuela",
    price: "79",
    description: "La opción más popular para autoescuelas en crecimiento.",
    features: [
      "Alumnos ilimitados",
      "Instructores ilimitados",
      "Todo el plan Autónomo",
      "Informes y estadísticas",
      "App móvil para instructores",
      "Recordatorios automáticos",
      "Soporte prioritario",
    ],
    cta: "Empezar gratis 30 días",
    highlighted: true,
    badge: "Más popular",
  },
  {
    name: "Franquicia",
    price: "Consultar",
    description: "Para grupos con varias academias y necesidades avanzadas.",
    features: [
      "Todo el plan Escuela",
      "Multi-sede centralizada",
      "API e integraciones",
      "Panel de administración",
      "Gestor de cuenta dedicado",
      "SLA garantizado",
    ],
    cta: "Hablar con ventas",
    highlighted: false,
  },
];
